{% set name = "basal-and-bark" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/basal_and_bark-{{ version }}.tar.gz
  sha256: 1d391d39c6eea50c4997d0483061d44c8b4e4932bcb5fe9d7bd89e0ca876482b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - folium
    - ipyleaflet
    - geopandas

test:
  imports:
    - basal_and_bark
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ZachDorm/basal_and_bark
  summary: Welcome to Basal and Bark, a spatial python package for working with forest data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ZachDorm
